component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/commons/.*
- ./bin/org/apache/commons/cli/.*
- ./bin/org/apache/commons/cli/avalon/.*
- ./bin/org/apache/commons/jexl/.*
- ./bin/org/apache/commons/jexl/bsf/.*
- ./bin/org/apache/jmeter/.*
- ./bin/org/apache/jmeter/assertions/.*
- ./bin/org/apache/jmeter/assertions/gui/.*
- ./bin/org/apache/jmeter/config/.*
- ./bin/org/apache/jmeter/config/gui/.*
- ./bin/org/apache/jmeter/control/.*
- ./bin/org/apache/jmeter/control/gui/.*
- ./bin/org/apache/jmeter/engine/.*
- ./bin/org/apache/jmeter/engine/event/.*
- ./bin/org/apache/jmeter/engine/util/.*
- ./bin/org/apache/jmeter/examples/.*
- ./bin/org/apache/jmeter/examples/sampler/.*
- ./bin/org/apache/jmeter/examples/sampler/gui/.*
- ./bin/org/apache/jmeter/examples/testbeans/.*
- ./bin/org/apache/jmeter/examples/testbeans/example1/.*
- ./bin/org/apache/jmeter/examples/testbeans/example2/.*
- ./bin/org/apache/jmeter/exceptions/.*
- ./bin/org/apache/jmeter/extractor/.*
- ./bin/org/apache/jmeter/extractor/gui/.*
- ./bin/org/apache/jmeter/functions/.*
- ./bin/org/apache/jmeter/functions/gui/.*
- ./bin/org/apache/jmeter/functions/util/.*
- ./bin/org/apache/jmeter/gui/.*
- ./bin/org/apache/jmeter/gui/action/.*
- ./bin/org/apache/jmeter/gui/tree/.*
- ./bin/org/apache/jmeter/gui/util/.*
- ./bin/org/apache/jmeter/images/.*
- ./bin/org/apache/jmeter/images/new/.*
- ./bin/org/apache/jmeter/junit/.*
- ./bin/org/apache/jmeter/junit/stubs/.*
- ./bin/org/apache/jmeter/modifiers/.*
- ./bin/org/apache/jmeter/modifiers/gui/.*
- ./bin/org/apache/jmeter/monitor/.*
- ./bin/org/apache/jmeter/monitor/model/.*
- ./bin/org/apache/jmeter/monitor/model/benchmark/.*
- ./bin/org/apache/jmeter/monitor/parser/.*
- ./bin/org/apache/jmeter/monitor/util/.*
- ./bin/org/apache/jmeter/plugin/.*
- ./bin/org/apache/jmeter/processor/.*
- ./bin/org/apache/jmeter/processor/gui/.*
- ./bin/org/apache/jmeter/protocol/.*
- ./bin/org/apache/jmeter/protocol/ftp/.*
- ./bin/org/apache/jmeter/protocol/ftp/config/.*
- ./bin/org/apache/jmeter/protocol/ftp/config/gui/.*
- ./bin/org/apache/jmeter/protocol/ftp/control/.*
- ./bin/org/apache/jmeter/protocol/ftp/control/gui/.*
- ./bin/org/apache/jmeter/protocol/ftp/sampler/.*
- ./bin/org/apache/jmeter/protocol/http/.*
- ./bin/org/apache/jmeter/protocol/http/config/.*
- ./bin/org/apache/jmeter/protocol/http/config/gui/.*
- ./bin/org/apache/jmeter/protocol/http/control/.*
- ./bin/org/apache/jmeter/protocol/http/control/gui/.*
- ./bin/org/apache/jmeter/protocol/http/gui/.*
- ./bin/org/apache/jmeter/protocol/http/modifier/.*
- ./bin/org/apache/jmeter/protocol/http/modifier/gui/.*
- ./bin/org/apache/jmeter/protocol/http/parser/.*
- ./bin/org/apache/jmeter/protocol/http/proxy/.*
- ./bin/org/apache/jmeter/protocol/http/proxy/gui/.*
- ./bin/org/apache/jmeter/protocol/http/sampler/.*
- ./bin/org/apache/jmeter/protocol/http/util/.*
- ./bin/org/apache/jmeter/protocol/http/util/accesslog/.*
- ./bin/org/apache/jmeter/protocol/http/visualizers/.*
- ./bin/org/apache/jmeter/protocol/java/.*
- ./bin/org/apache/jmeter/protocol/java/config/.*
- ./bin/org/apache/jmeter/protocol/java/config/gui/.*
- ./bin/org/apache/jmeter/protocol/java/control/.*
- ./bin/org/apache/jmeter/protocol/java/control/gui/.*
- ./bin/org/apache/jmeter/protocol/java/sampler/.*
- ./bin/org/apache/jmeter/protocol/java/test/.*
- ./bin/org/apache/jmeter/protocol/jdbc/.*
- ./bin/org/apache/jmeter/protocol/jdbc/config/.*
- ./bin/org/apache/jmeter/protocol/jdbc/sampler/.*
- ./bin/org/apache/jmeter/protocol/jms/.*
- ./bin/org/apache/jmeter/protocol/jms/client/.*
- ./bin/org/apache/jmeter/protocol/jms/control/.*
- ./bin/org/apache/jmeter/protocol/jms/control/gui/.*
- ./bin/org/apache/jmeter/protocol/jms/sampler/.*
- ./bin/org/apache/jmeter/protocol/ldap/.*
- ./bin/org/apache/jmeter/protocol/ldap/config/.*
- ./bin/org/apache/jmeter/protocol/ldap/config/gui/.*
- ./bin/org/apache/jmeter/protocol/ldap/control/.*
- ./bin/org/apache/jmeter/protocol/ldap/control/gui/.*
- ./bin/org/apache/jmeter/protocol/ldap/sampler/.*
- ./bin/org/apache/jmeter/protocol/mail/.*
- ./bin/org/apache/jmeter/protocol/mail/sampler/.*
- ./bin/org/apache/jmeter/protocol/mail/sampler/gui/.*
- ./bin/org/apache/jmeter/protocol/smtp/.*
- ./bin/org/apache/jmeter/protocol/smtp/sampler/.*
- ./bin/org/apache/jmeter/protocol/smtp/sampler/gui/.*
- ./bin/org/apache/jmeter/protocol/smtp/sampler/protocol/.*
- ./bin/org/apache/jmeter/protocol/smtp/sampler/tools/.*
- ./bin/org/apache/jmeter/protocol/tcp/.*
- ./bin/org/apache/jmeter/protocol/tcp/config/.*
- ./bin/org/apache/jmeter/protocol/tcp/config/gui/.*
- ./bin/org/apache/jmeter/protocol/tcp/control/.*
- ./bin/org/apache/jmeter/protocol/tcp/control/gui/.*
- ./bin/org/apache/jmeter/protocol/tcp/sampler/.*
- ./bin/org/apache/jmeter/report/.*
- ./bin/org/apache/jmeter/report/engine/.*
- ./bin/org/apache/jmeter/report/gui/.*
- ./bin/org/apache/jmeter/report/gui/action/.*
- ./bin/org/apache/jmeter/report/gui/tree/.*
- ./bin/org/apache/jmeter/report/writers/.*
- ./bin/org/apache/jmeter/report/writers/gui/.*
- ./bin/org/apache/jmeter/reporters/.*
- ./bin/org/apache/jmeter/reporters/gui/.*
- ./bin/org/apache/jmeter/sampler/.*
- ./bin/org/apache/jmeter/sampler/gui/.*
- ./bin/org/apache/jmeter/samplers/.*
- ./bin/org/apache/jmeter/samplers/gui/.*
- ./bin/org/apache/jmeter/save/.*
- ./bin/org/apache/jmeter/save/converters/.*
- ./bin/org/apache/jmeter/services/.*
- ./bin/org/apache/jmeter/swing/.*
- ./bin/org/apache/jmeter/testbeans/.*
- ./bin/org/apache/jmeter/testbeans/gui/.*
- ./bin/org/apache/jmeter/testelement/.*
- ./bin/org/apache/jmeter/testelement/property/.*
- ./bin/org/apache/jmeter/threads/.*
- ./bin/org/apache/jmeter/threads/gui/.*
- ./bin/org/apache/jmeter/timers/.*
- ./bin/org/apache/jmeter/timers/gui/.*
- ./bin/org/apache/jmeter/util/.*
- ./bin/org/apache/jmeter/util/keystore/.*
- ./bin/org/apache/jmeter/visualizers/.*
- ./bin/org/apache/jmeter/visualizers/gui/.*
- ./bin/org/apache/jorphan/.*
- ./bin/org/apache/jorphan/collections/.*
- ./bin/org/apache/jorphan/gui/.*
- ./bin/org/apache/jorphan/gui/layout/.*
- ./bin/org/apache/jorphan/io/.*
- ./bin/org/apache/jorphan/logging/.*
- ./bin/org/apache/jorphan/math/.*
- ./bin/org/apache/jorphan/reflect/.*
- ./bin/org/apache/jorphan/test/.*
- ./bin/org/apache/jorphan/util/.*
- ./bin/test/.*
- ./bin/woolfel/.*
- ./extras/.*
- ./lib/.*
- ./lib/opt/.*
- ./res/.*
- ./res/META-INF/.*
- ./test/.*
- ./xdocs/.*
- ./xdocs/css/.*
- ./xdocs/demos/.*
- ./xdocs/extending/.*
- ./xdocs/images/.*
- ./xdocs/images/screenshots/.*
- ./xdocs/images/screenshots/assertion/.*
- ./xdocs/images/screenshots/ftp-config/.*
- ./xdocs/images/screenshots/ftptest/.*
- ./xdocs/images/screenshots/http-config/.*
- ./xdocs/images/screenshots/jdbc-config/.*
- ./xdocs/images/screenshots/jdbctest/.*
- ./xdocs/images/screenshots/jms/.*
- ./xdocs/images/screenshots/ldaptest/.*
- ./xdocs/images/screenshots/logic-controller/.*
- ./xdocs/images/screenshots/remote/.*
- ./xdocs/images/screenshots/timers/.*
- ./xdocs/images/screenshots/webtest/.*
- ./xdocs/localising/.*
- ./xdocs/presentation/.*
- ./xdocs/stylesheets/.*
- ./xdocs/usermanual/.*
